name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python version
        run: python --version

      - name: pip install
        run: pip install -r requirements.txt

      - name: train model
        run: python model/train.py

      - name: Show secret values (for debug only)
        run: |
          echo "DOCKER_USER=${{ secrets.DOCKER_USER }}"
          echo "MODEL_NAME=${{ secrets.MODEL_NAME }}"
        
      - name: docker build
        run: docker buildx build -t ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }} .

      - name: show images
        run: docker images
